"""
===============================================================================
File:        run.py
Author:      JP Ueberbach
Created:     2026-03-01

Description:
    Command-line entry point for the MilkyWay diagnostic suite.

    This module provides a unified CLI for running post-training forensic
    diagnostics on neuro-evolved MilkyWay models. It orchestrates multiple
    diagnostic tools, allowing them to be executed individually or as a
    chained validation pipeline.

    Supported diagnostics include:
        - Static model inspection (weights, normalization, gene importance)
        - Bulk threshold scanning for optimal decision boundaries
        - Walk-forward simulation with zero look-ahead bias

    The module is intentionally procedural and IO-heavy. It performs no
    learning, mutation, or model updates. Its sole responsibility is
    orchestration and result emission.

Responsibilities:
    - Parse and validate command-line arguments
    - Dispatch diagnostic tools based on selected mode
    - Coordinate data flow between diagnostics in "full" mode
    - Persist walk-forward results to disk

Design Notes:
    - Uses argparse with custom error handling for better UX
    - Defaults are conservative and explicit
    - All diagnostics operate in read-only mode on model checkpoints
===============================================================================
"""
import sys
import argparse
from datetime import datetime, timezone
from ml.diagnostics.inspector import ModelInspector
from ml.diagnostics.stepper import ForensicWalkForward
from ml.diagnostics.scanner import ThresholdScanner


class MilkyWayParser(argparse.ArgumentParser):
    """
    Custom ArgumentParser with aggressive error reporting.

    This parser overrides the default error behavior to ensure that
    users always see the full help text and usage examples when
    invalid arguments are supplied.
    """

    def error(self, message):
        """
        Handles argument parsing errors.

        Args:
            message (str): The error message generated by argparse.

        Returns:
            None
        """
        # Write a clearly marked error message to standard error
        sys.stderr.write(f"\n🚨 [Argument Error]: {message}\n\n")

        # Print the full help text so the user can immediately recover
        self.print_help()

        # Exit with the conventional argparse error code
        sys.exit(2)


def main():
    """
    Entry point for the MilkyWay diagnostic CLI.

    This function parses command-line arguments, resolves the selected
    diagnostic mode, and executes the appropriate tools in the correct
    order. In "full" mode, outputs from earlier diagnostics are fed
    directly into subsequent ones.
    """
    # Multi-line epilog containing extended usage examples
    extended_help_examples = """
================================================================================
MILKYWAY DIAGNOSTIC SUITE - USAGE EXAMPLES
================================================================================

1. INSPECT MODE: Gene & Topology Analysis
   Analyze the model's weights, Z-means, and calculate gene impact without 
   needing to load market data.
   
   Command:
     python run_diagnostics.py --mode inspect --model checkpoints/model-best.pt

2. SCAN MODE: Discover the "Sniper" Threshold
   Run vectorized bulk inference across an entire dataset to find the exact 
   threshold that yields 1.0000 Precision and the maximum F1 Score.
   
   Command:
     python run_diagnostics.py --mode scan --model checkpoints/model-best.pt \\
       --symbol EUR-USD --timeframe 1d --start 2025-01-01

3. WALK-FORWARD MODE: Candle-by-Candle Forensic Test
   Simulate live market execution step-by-step with zero look-ahead bias. 
   Optionally test a specific threshold or limit the number of steps.
   
   Command:
     python run_diagnostics.py --mode walk --model checkpoints/model-best.pt \\
       --symbol GBP-USD --start 2025-06-01 --threshold 0.8687 --steps 100

4. FULL SUITE: The Ultimate Validation Run
   Automatically chains all tools: Inspects genes -> Scans for the Sniper 
   threshold -> Feeds that threshold directly into a Walk-Forward test.
   
   Command:
     python run_diagnostics.py --mode full --model checkpoints/model-best.pt \\
       --symbol GBP-USD --timeframe 4h --start 2026-01-01
================================================================================
"""

    # Instantiate the custom argument parser with extended formatting enabled
    parser = MilkyWayParser(
        description="MilkyWay Full Diagnostic Suite: Forensic Tooling for Neuro-Evolved Models.",
        epilog=extended_help_examples,
        formatter_class=argparse.RawDescriptionHelpFormatter
    )

    # Define the mandatory execution mode argument
    parser.add_argument(
        "--mode",
        type=str,
        required=True,
        choices=["inspect", "walk", "scan", "full"],
        help="Diagnostic mode: 'inspect', 'walk', 'scan', or 'full'."
    )

    # Define the mandatory model checkpoint path
    parser.add_argument(
        "--model",
        type=str,
        required=True,
        help="Path to the .pt model checkpoint."
    )

    # Optional arguments used by scan and walk-forward diagnostics
    parser.add_argument("--symbol", type=str, default="GBP-USD",
                        help="Fabric matter symbol (e.g., GBP-USD).")
    parser.add_argument("--timeframe", type=str, default="1d",
                        help="Fabric timeframe (e.g., 1d, 4h).")
    parser.add_argument("--center", type=str,
                        default="example-pivot-finder_10_bottoms",
                        help="Target indicator to map against.")
    parser.add_argument("--start", type=str, default="2025-01-01",
                        help="Start date (YYYY-MM-DD) for validation.")
    parser.add_argument("--steps", type=int, default=-1,
                        help="Max steps for walk-forward. -1 for entire available range.")
    parser.add_argument("--threshold", type=float, default=None,
                        help="Override model's default trigger threshold in walk mode.")

    # If the user ran the script with no arguments at all, show help and exit
    if len(sys.argv) == 1:
        parser.print_help(sys.stderr)
        sys.exit(1)

    # Parse all command-line arguments into a namespace
    args = parser.parse_args()

    # Convert the start date string into a UTC epoch timestamp in milliseconds
    epoch_ms = int(
        datetime.strptime(args.start, "%Y-%m-%d")
        .replace(tzinfo=timezone.utc)
        .timestamp() * 1000
    )

    # ------------------------------------------------------------------
    # 1. Inspector Mode (static model analysis)
    # ------------------------------------------------------------------
    if args.mode in ["inspect", "full"]:
        # Initialize the model inspector using the provided checkpoint
        inspector = ModelInspector(model_path=args.model)

        # Execute the inspection routine
        inspector.run()

    # ------------------------------------------------------------------
    # 2. Threshold Scanner Mode (bulk inference threshold search)
    # ------------------------------------------------------------------
    if args.mode in ["scan", "full"]:
        # Initialize the threshold scanner with market and model parameters
        scanner = ThresholdScanner(
            model_path=args.model,
            center=args.center,
            symbol=args.symbol,
            timeframe=args.timeframe,
            start_ms=epoch_ms,
            options={"use_cache": False}
        )

        # Execute the scan using 1000 steps for fine-grained resolution
        sniper_t, f1_t = scanner.run(steps=1000)

        # If running the full pipeline, automatically propagate the threshold
        if args.mode == "full" and args.threshold is None and sniper_t is not None:
            args.threshold = sniper_t
            print(
                f"⚙️ [Auto-Link]: Feeding Sniper Threshold "
                f"({sniper_t:.4f}) into Walk-Forward Stepper..."
            )

    # ------------------------------------------------------------------
    # 3. Walk-Forward Mode (step-by-step execution simulation)
    # ------------------------------------------------------------------
    if args.mode in ["walk", "full"]:
        # Initialize the walk-forward stepper with resolved parameters
        stepper = ForensicWalkForward(
            model_path=args.model,
            center=args.center,
            symbol=args.symbol,
            timeframe=args.timeframe,
            start_ms=epoch_ms,
            threshold=args.threshold,
            options={"use_cache": False}
        )

        # Execute the walk-forward simulation
        results_df = stepper.run(max_steps=args.steps)

        # Persist results to disk if any rows were produced
        if not results_df.empty:
            out_file = f"walk_forward_{args.symbol}_{stepper.model_name}.csv"
            results_df.to_csv(out_file, index=False)
            print(f"💾 Saved walk-forward payload to: {out_file}")


# Standard Python entry-point guard
if __name__ == "__main__":
    main()