"""
===============================================================================
File:        actions.py
Author:      JP Ueberbach
Created:     2026-03-03

Description:
    Action execution framework for the ML alerting system.

    This module defines:

        - A BaseAction interface for all alert actions
        - Concrete action implementations (Webhook, Gmail, Local Email)
        - A centralized ActionFactory for dispatching actions by type

    Responsibilities:
        - Encapsulate side-effect logic (HTTP calls, email sending)
        - Provide a unified execution interface
        - Enable easy extension for additional action types
        - Centralize action registration and dispatch logic

    Design Overview:
        - Each action implements the BaseAction interface.
        - ActionFactory maintains a registry of action instances.
        - The engine dispatches actions dynamically based on configuration.

    This design ensures that alert triggering logic remains decoupled
    from external integration mechanisms.
===============================================================================
"""

import requests
import smtplib
from email.message import EmailMessage
from typing import Dict, Any


class BaseAction:
    """
    Abstract base class for alert actions.

    All action implementations must inherit from this class
    and implement the execute() method.
    """

    def execute(self, params: Dict[str, Any], payload: Dict[str, Any]):
        """
        Execute the action.

        Args:
            params (Dict[str, Any]):
                Action-specific configuration parameters.

            payload (Dict[str, Any]):
                Data payload generated by the alert engine.

        Raises:
            NotImplementedError:
                If not implemented by subclass.
        """
        # Enforce implementation in subclasses
        raise NotImplementedError("Subclasses must implement execute()")


class WebhookAction(BaseAction):
    """
    Sends alert payloads to an external HTTP endpoint.

    Supports POST and GET methods.
    """

    def execute(self, params: Dict[str, Any], payload: Dict[str, Any]):
        """
        Execute webhook action.

        Args:
            params (Dict[str, Any]):
                Must contain:
                    - uri (str): Target endpoint URL
                    - method (str, optional): HTTP method (default POST)

            payload (Dict[str, Any]):
                Alert data to send to the endpoint.
        """
        # Retrieve endpoint URI from configuration
        uri = params.get("uri")

        # Retrieve HTTP method (default to POST)
        method = params.get("method", "POST").upper()

        try:
            # Send HTTP POST request with JSON payload
            if method == "POST":
                response = requests.post(uri, json=payload, timeout=10)

            # Send HTTP GET request with query parameters
            elif method == "GET":
                response = requests.get(uri, params=payload, timeout=10)

            # Log successful transmission status
            print(f"[Webhook] Sent to {uri} - Status: {response.status_code}")

        except Exception as e:
            # Log failure during HTTP communication
            print(f"[Webhook] Failed to send to {uri}: {e}")


class EmailActionGmail(BaseAction):
    """
    Sends alert emails using Gmail SMTP with TLS.

    Requires valid Gmail credentials (App Password recommended).
    """

    def execute(self, params: Dict[str, Any], payload: Dict[str, Any]):
        """
        Execute Gmail email action.

        Args:
            params (Dict[str, Any]):
                Expected keys:
                    - address (str): Recipient email
                    - subject (str, optional): Email subject
                    - smtp_server (str, optional)
                    - smtp_port (int, optional)
                    - username (str): SMTP username
                    - password (str): SMTP password
                    - from_address (str, optional)

            payload (Dict[str, Any]):
                Alert data to include in email body.
        """
        # Log execution entry for debugging
        print("Executing action gmail")

        # Extract recipient address
        address = params.get("address")

        # Extract email subject with default fallback
        subject = params.get("subject", "Alert Triggered")

        # Retrieve SMTP configuration (default Gmail server settings)
        smtp_server = params.get("smtp_server", "smtp.gmail.com")
        smtp_port = int(params.get("smtp_port", 587))
        username = params.get("username")
        password = params.get("password")

        # Determine sender address (fallback to username)
        from_address = params.get("from_address", username)

        # Validate credentials presence
        if not username or not password:
            print(f"[Email Error] Missing credentials for {address}. Cannot send.")
            return

        # Construct email message
        msg = EmailMessage()

        # Set plain text body including alert payload
        msg.set_content(f"Alert triggered with data:\n{payload}")

        # Set message headers
        msg["Subject"] = subject
        msg["From"] = from_address
        msg["To"] = address

        try:
            # Establish SMTP connection
            with smtplib.SMTP(smtp_server, smtp_port) as server:

                # Identify client to SMTP server
                server.ehlo()

                # Upgrade connection to TLS encryption
                server.starttls()

                # Re-identify after TLS handshake
                server.ehlo()

                # Authenticate using provided credentials
                server.login(username, password)

                # Send composed email message
                server.send_message(msg)

            # Log success
            print(f"[Email] Successfully sent via Gmail to {address}")

        except Exception as e:
            # Log failure details
            print(f"[Email] Failed to send via Gmail to {address}: {e}")


class EmailAction(BaseAction):
    """
    Sends alert emails via a local SMTP server.

    Intended for development environments (e.g., MailHog).
    """

    def execute(self, params: Dict[str, Any], payload: Dict[str, Any]):
        """
        Execute local email action.

        Args:
            params (Dict[str, Any]):
                Expected keys:
                    - address (str): Recipient email
                    - subject (str, optional)

            payload (Dict[str, Any]):
                Alert data to include in email body.
        """
        # Retrieve recipient address
        address = params.get("address")

        # Retrieve subject with default fallback
        subject = params.get("subject", "Alert Triggered")

        # Construct email message
        msg = EmailMessage()

        # Set plain text body including payload data
        msg.set_content(f"Alert triggered with data:\n{payload}")

        # Set message headers
        msg["Subject"] = subject
        msg["From"] = "alerts@yourdomain.com"
        msg["To"] = address

        try:
            # Connect to local SMTP server (development default)
            with smtplib.SMTP("localhost", 1025) as server:

                # Send email message
                server.send_message(msg)

            # Log success
            print(f"[Email] Sent to {address}")

        except Exception as e:
            # Log failure details
            print(f"[Email] Failed to send to {address}: {e}")


class ActionFactory:
    """
    Centralized factory for dispatching alert actions.

    Maintains a registry mapping action type strings
    to concrete action instances.
    """

    # Static registry of available action implementations
    _actions = {
        "webhook": WebhookAction(),
        "gmail": EmailActionGmail(),
        "mail": EmailAction(),
    }

    @classmethod
    def dispatch(
        cls,
        action_type: str,
        params: Dict[str, Any],
        payload: Dict[str, Any],
    ):
        """
        Dispatch an action based on its type.

        Args:
            action_type (str):
                Type identifier of the action.

            params (Dict[str, Any]):
                Action-specific configuration parameters.

            payload (Dict[str, Any]):
                Alert payload to pass to the action.
        """
        # Retrieve action instance from registry (case-insensitive)
        action = cls._actions.get(action_type.lower())

        # Execute action if found
        if action:
            action.execute(params, payload)

        # Log error if action type is unknown
        else:
            print(f"[Action Error] Unknown action type: {action_type}")